/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import javax.swing.JButton;

/**
 *
 * @author Weerakoon
 */
public class SwitchBoard extends javax.swing.JFrame {

    /**
     * Creates new form SwitchBoard
     */
    public SwitchBoard() {
        initComponents();
        Access();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddDoctor = new javax.swing.JButton();
        btnAddBooking = new javax.swing.JButton();
        btnAddEmployee = new javax.swing.JButton();
        btnViewBooking = new javax.swing.JButton();
        btnViewPatients = new javax.swing.JButton();
        btnAddPatient = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnViewDoctor = new javax.swing.JButton();
        btnViewEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Switch Board");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddDoctor.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnAddDoctor.setText("Add Doctor");
        btnAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 200, 250, 41));

        btnAddBooking.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnAddBooking.setText("Add Booking");
        btnAddBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 121, 250, 41));

        btnAddEmployee.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 121, 250, 41));

        btnViewBooking.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnViewBooking.setText("View Bookings");
        btnViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookingActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 200, 241, 41));

        btnViewPatients.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnViewPatients.setText("View Patients");
        btnViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 347, 241, 41));

        btnAddPatient.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnAddPatient.setText("Add Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 200, 250, 41));

        jLabel3.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Navaloka Hospital");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 874, 59));

        btnViewDoctor.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnViewDoctor.setText("View Doctors");
        btnViewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 275, 241, 41));

        btnViewEmployee.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        btnViewEmployee.setText("View Employee");
        btnViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 121, 241, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Access(){
    if(!AppDetails.loggerID.toLowerCase().equals("admin")){
    btnAddEmployee.setVisible(false);
    btnAddDoctor.setVisible(false);
    }
        
    }
    
    
    private void btnViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientsActionPerformed

        new ViewPatient().setVisible(true);
    }//GEN-LAST:event_btnViewPatientsActionPerformed

    private void btnAddBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookingActionPerformed

        new AddBooking().setVisible(true);
    }//GEN-LAST:event_btnAddBookingActionPerformed

    private void btnViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDoctorActionPerformed

        new ViewDoctor().setVisible(true);
    }//GEN-LAST:event_btnViewDoctorActionPerformed

    private void btnAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDoctorActionPerformed

        new AddDoctor().setVisible(true);

    }//GEN-LAST:event_btnAddDoctorActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed

        new AddPatient().setVisible(true);

    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed

        new AddEmployee().setVisible(true);


    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingActionPerformed

        new ViewBooking().setVisible(true);


    }//GEN-LAST:event_btnViewBookingActionPerformed

    private void btnViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeActionPerformed

        new ViewEmployee().setVisible(true);


    }//GEN-LAST:event_btnViewEmployeeActionPerformed

    public JButton getBtnAddDoctor() {
        return btnAddDoctor;
    }

    public JButton getBtnAddEmployee() {
        return btnAddEmployee;
    }

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SwitchBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SwitchBoard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBooking;
    private javax.swing.JButton btnAddDoctor;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnViewBooking;
    private javax.swing.JButton btnViewDoctor;
    private javax.swing.JButton btnViewEmployee;
    private javax.swing.JButton btnViewPatients;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
