/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Wishwa Prabodha
 */
public class ViewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmployee
     */
    public ViewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtEmployeeNIC = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Navaloka Hospital");

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Employee NIC", "Employee Telephone", "Employee Address", "Username", "Password", "Access"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Employee Name :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Employee ID :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Employee NIC :");

        btnSearch.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmployeeNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmployeeNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if (!txtEmployeeID.getText().equals("")) {
            int id = Integer.parseInt(txtEmployeeID.getText());

            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;
            String rPass = null;
            String rAcc = null;
            String SearchQ = "Select * from emp where empId=?";
            int i = 0;
            try {
                con = DataAccess.connect();
                pst = con.prepareStatement(SearchQ);
                pst.setInt(1, id);
                rs = pst.executeQuery();
                if (rs.next()) {
                    System.out.println("This is: " + rs.getInt("empID"));

                    tblEmployee.getModel().setValueAt(rs.getInt("empID"), 0, 0);
                    tblEmployee.getModel().setValueAt(rs.getString("empName"), 0, 1);
                    tblEmployee.getModel().setValueAt(rs.getString("empNIC"), 0, 2);
                    tblEmployee.getModel().setValueAt(rs.getInt("empContactNo"), 0, 3);
                    tblEmployee.getModel().setValueAt(rs.getString("empAddress"), 0, 4);
                    tblEmployee.getModel().setValueAt(rs.getString("empUsername"), 0, 5);
                    tblEmployee.getModel().setValueAt(rs.getString("empPassword"), 0, 6);
                    tblEmployee.getModel().setValueAt(rs.getString("empAccess"), 0, 7);

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (!txtEmployeeName.getText().equals("")) {
            String name = txtEmployeeName.getText();

            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;
            String rPass = null;
            String rAcc = null;
            String SearchQ = "Select * from emp where empName=?";
            int i = 0;
            try {
                con = DataAccess.connect();
                pst = con.prepareStatement(SearchQ);
                pst.setString(1, name);
                rs = pst.executeQuery();
                while (rs.next()) {

                    tblEmployee.getModel().setValueAt(rs.getInt("empID"), i, 0);
                    tblEmployee.getModel().setValueAt(rs.getInt("empName"), i, 1);
                    tblEmployee.getModel().setValueAt(rs.getInt("empNIC"), i, 2);
                    tblEmployee.getModel().setValueAt(rs.getInt("empContactNo"), i, 3);
                    tblEmployee.getModel().setValueAt(rs.getInt("empAddress"), i, 4);
                    tblEmployee.getModel().setValueAt(rs.getInt("empUsername"), i, 5);
                    tblEmployee.getModel().setValueAt(rs.getString("empPassword"), i, 6);
                    tblEmployee.getModel().setValueAt(rs.getString("empAccess"), i, 7);
                    i++;

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        } else if (!txtEmployeeNIC.getText().equals("")) {
            String name = txtEmployeeNIC.getText();

            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;
            String rPass = null;
            String rAcc = null;
            String SearchQ = "Select * from emp where empNIC=?";
            int i = 0;
            try {
                con = DataAccess.connect();
                pst = con.prepareStatement(SearchQ);
                pst.setString(1, name);
                rs = pst.executeQuery();
                while (rs.next()) {

                    tblEmployee.getModel().setValueAt(rs.getInt("empID"), i, 0);
                    tblEmployee.getModel().setValueAt(rs.getInt("empName"), i, 1);
                    tblEmployee.getModel().setValueAt(rs.getInt("empNIC"), i, 2);
                    tblEmployee.getModel().setValueAt(rs.getInt("empContactNo"), i, 3);
                    tblEmployee.getModel().setValueAt(rs.getInt("empAddress"), i, 4);
                    tblEmployee.getModel().setValueAt(rs.getInt("empUsername"), i, 5);
                    tblEmployee.getModel().setValueAt(rs.getString("empPassword"), i, 6);
                    tblEmployee.getModel().setValueAt(rs.getString("empAccess"), i, 7);
                    i++;

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }


    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeNIC;
    private javax.swing.JTextField txtEmployeeName;
    // End of variables declaration//GEN-END:variables
}
